### ISSUE TITLE
compeletion of requirements readme file

### ISSUE THREAD

**Issue by 99003783** [99003783/T7_SDLC_CALC#3]
complete the part of cost and features, defining our system.

**Comment by 99003778** [comment]
Calculator                    Cost                   Features
Basic                            170                   Addition, Subtraction, Multiplication and Division
Scientific                      750                   log, natural log and trignometric functions
Engineer scientific       1600                  42 built-in Physical Constants
Financial                      3000                  The financial calculators usually have five important keys that represent the 'variables'
Printing                       5000                  You can press TIME key to display current time and date. You can press REPRINT key to 
                                                              reprint operation and calculation results.
Graphical                     11800                plot graphs and even solve equations
Programmable Scientific       15000      Programmable Scientific Calculator with 664 Functions.With Natural Textbook 
                                                              Display so your functions and equations look same as in your textbook.Probability, 
                                                              Calculus, Permutation Combination, Random Number Calculation features.Statistics 
                                                              (List-based Statistics, Standard deviation, Regression analysis)

**Comment by 99003778** [comment]
Task completed

**Comment by 99003783** [comment]
Thankyou
